### ISSUE TITLE
Feature Request: use Homebrew Cask for distribution

### ISSUE THREAD

**Issue by hamsternik** [nothingmagical/ZoomIn#4]
Hi Sam!

I'm really appreciate the work you have done! It's really nice when you have a several Zoom conferences in a day to just stop click & close pages. Thanks man!

My suggestion about the distribution: can you add support of the Homebrew Cask for that extension? It would be great to have the latest update via the scheduled Homebrew updates instead of polling your gh page or check notifications to be aware about the new release.
What do you think so?

**Comment by soffes** [comment]
It's already on Homebrew Cask :)
